fun main(args: Array<String>) {
    val portoAlegre = Vertice("Porto Alegre")
    val florianopolis = Vertice("Florianopolis")
    val saoPaulo = Vertice("São Paulo")
    val saoJoseDosCampos = Vertice("São Jose dos Campos")
    val caraguatatuba = Vertice("Caraguatatuba")
    val rioDeJaneiro = Vertice("Rio De Janeiro")
    val patoBranco = Vertice("Pato Branco")
    val piracicaba = Vertice("Piracicaba")

    portoAlegre.getVerticeConnection(Aresta(florianopolis, 462000))
    florianopolis.getVerticeConnection(Aresta(saoPaulo, 969000))
    saoPaulo.getVerticeConnection(Aresta(florianopolis, 969000))
    florianopolis.getVerticeConnection(Aresta(patoBranco, 632000))
    patoBranco.getVerticeConnection(Aresta(piracicaba, 802000))
    piracicaba.getVerticeConnection(Aresta(patoBranco, 802000))
    saoPaulo.getVerticeConnection(Aresta(saoJoseDosCampos, 91000))
    saoPaulo.getVerticeConnection(Aresta(piracicaba, 157000))
    piracicaba.getVerticeConnection(Aresta(saoPaulo, 157000))
    saoJoseDosCampos.getVerticeConnection(Aresta(caraguatatuba, 174000))
    caraguatatuba.getVerticeConnection(Aresta(rioDeJaneiro, 422000))
    rioDeJaneiro.getVerticeConnection(Aresta(caraguatatuba, 422000))

    val map = Grafo()
    map.addVertice(portoAlegre)
    map.addVertice(florianopolis)
    map.addVertice(saoPaulo)
    map.addVertice(caraguatatuba)
    map.addVertice(saoJoseDosCampos)
    map.addVertice(rioDeJaneiro)
    map.addVertice(patoBranco)
    map.addVertice(piracicaba)

    map.printShortestRoutes(portoAlegre, piracicaba)
}