fun main(args: Array<String>) {
    val portoAlegre = Vertice("Porto Alegre")
    val florianopolis = Vertice("Florianopolis")
    val saoPaulo = Vertice("São Paulo")
    val saoJoseDosCampos = Vertice("São Jose dos Campos")
    val caraguatatuba = Vertice("Caraguatatuba")
    val rioDeJaneiro = Vertice("Rio De Janeiro")
    val patoBranco = Vertice("Pato Branco")
    val piracicaba = Vertice("Piracicaba")

    portoAlegre.getVerticeConnection(Aresta(florianopolis, 462000))
    florianopolis.getVerticeConnection(Aresta(saoPaulo, 969000))
    saoPaulo.getVerticeConnection(Aresta(florianopolis, 969000))
    florianopolis.getVerticeConnection(Aresta(patoBranco, 632000))
    patoBranco.getVerticeConnection(Aresta(piracicaba, 802000))
    piracicaba.getVerticeConnection(Aresta(patoBranco, 802000))
    saoPaulo.getVerticeConnection(Aresta(saoJoseDosCampos, 91000))
    saoPaulo.getVerticeConnection(Aresta(piracicaba, 157000))
    piracicaba.getVerticeConnection(Aresta(saoPaulo, 157000))
    saoJoseDosCampos.getVerticeConnection(Aresta(caraguatatuba, 174000))
    caraguatatuba.getVerticeConnection(Aresta(rioDeJaneiro, 422000))
    rioDeJaneiro.getVerticeConnection(Aresta(caraguatatuba, 422000))

    val map = Grafo()
    map.addVertice(portoAlegre)
    map.addVertice(florianopolis)
    map.addVertice(saoPaulo)
    map.addVertice(caraguatatuba)
    map.addVertice(saoJoseDosCampos)
    map.addVertice(rioDeJaneiro)
    map.addVertice(patoBranco)
    map.addVertice(piracicaba)

    map.printShortestRoutes(portoAlegre)

    /*val casaDoJoao = Vertice("Casa Do João")
    val quitanda = Vertice("Quitanda")
    val pracinha = Vertice("Pracinha")
    val armazen = Vertice("Armazem")
    val cancela = Vertice("Cancela")
    val escola = Vertice("Escola")
    val bancaDeJornal = Vertice("Banca De Jornal")


    casaDoJoao.getVerticeConnection(Aresta(armazen, 5))
    casaDoJoao.getVerticeConnection(Aresta(pracinha, 6))
    casaDoJoao.getVerticeConnection(Aresta(quitanda, 10))
    armazen.getVerticeConnection(Aresta(bancaDeJornal,13))
    bancaDeJornal.getVerticeConnection(Aresta(escola,3))
    pracinha.getVerticeConnection(Aresta(cancela,6))
    pracinha.getVerticeConnection(Aresta(quitanda,3))
    pracinha.getVerticeConnection(Aresta(bancaDeJornal,11))
    quitanda.getVerticeConnection(Aresta(pracinha,3))
    quitanda.getVerticeConnection(Aresta(bancaDeJornal,6))
    quitanda.getVerticeConnection(Aresta(cancela,4))
    quitanda.getVerticeConnection(Aresta(casaDoJoao,10))
    cancela.getVerticeConnection(Aresta(escola,8))
    cancela.getVerticeConnection(Aresta(pracinha,6))
    cancela.getVerticeConnection(Aresta(quitanda,4))

    val map2 = NavigationMap()
    map2.addVertice(casaDoJoao)
    map2.addVertice(quitanda)
    map2.addVertice(pracinha)
    map2.addVertice(armazen)
    map2.addVertice(cancela)
    map2.addVertice(escola)
    map2.addVertice(bancaDeJornal)

    map2.printShortestRoutes(casaDoJoao)*/
}